FROM microsoft/aspnetcore-build AS build

WORKDIR /publish

COPY ./Sample.csproj ./
RUN dotnet restore

COPY ./ .
RUN dotnet publish --output ./out

FROM microsoft/microsoft/aspnetcore

WORKDIR /app
COPY --from=build /publish/out .
ENV ASPNETCORE_URLS="https://0.0.0.0:80"

ENTRYPOINT [ "dotnet", "sample.dll" ]